### ISSUE TITLE
localizer

### ISSUE THREAD

**Issue by xiaoxiaobx** [alexs7/ACG_Localizer#1]
@tsattler
When I compile and run acg_localizer.cc, the result is as follows:,What's the problem?
And run other .cc code with errors.
`_______________________________________________________________________________                                                                                                                      
 -        Localization method. Implementation of the localization framework proposed in the ICCV 2011 paper               - 
 -          T. Sattler, B. Leibe, L. Kobbelt. Fast Image-Based Localization using Direct 2D-to-3D Matching.               - 
 -                               2011 by Torsten Sattler (tsattler@cs.rwth-aachen.de)                                     - 
 -                                                                                                                        - 
 - usage: acg_localizer list nb_trees nb_cluster clusters descriptors mode in_ratio max_corr results                      - 
 - Parameters:                                                                                                            - 
 -  list                                                                                                                  - 
 -     List containing the filenames of all the .key files that should be used as query. It is assumed that the           - 
 -     corresponding images have the same filename except of ending in .jpg.                                                                                                                                                                   - 
 -  nb_tree                                                                                                               - 
 -     The number of trees to use for the random kd-forest that is employed to do the assignments of 2D features to       - 
 -     visual words. Set to 1 for all experiments in the paper.                                                           - 
 -                                                                                                                        - 
 -  nb_cluster                                                                                                            - 
 -     The number of clusters in the file containing the cluster centers. The number of cluster must be the same          - 
 -     as for the assignments computed by compute_desc_assignments.                                                       - 
 -                                                                                                                        - 
 -  clusters                                                                                                              - 
 -     The cluster centers (visual words), stored in a textfile consisting of nb_clusters * 128 floating point values.    - 
 -                                                                                                                        - 
 -  descriptors                                                                                                           - 
 -     The assignments assigning descriptors (and 3D points) to visual words, computed by compute_desc_assignments.       - 
 -                                                                                                                        - 
 -  mode                                                                                                                  - 
 -     The way the descriptors in the assignments file are stored (0 = unsigned char, 1 = float). Set mode to 2 to        - 
 -     allow multiple descriptors (unsigned char) of the same point to be mapped to the same visual word.                 - 
 -                                                                                                                        - 
 -  in_ratio                                                                                                              - 
 -     Assumed minimal inlier ratio for RANSAC.                                                                           - 
 -                                                                                                                        - 
 -  max_cor                                                                                                               - 
 -     If max_cor correspondences are found, the search for more correspondences is terminated.                           - 
 -     Set to 0 to disable early termination.                                                                             - 
 -                                                                                                                        - 
 -  results                                                                                                               - 
 -     The program will write the results of the localization into a text file of name "results". It has the following  - 
 -     format, where every line in the file belongs to one query image and has the format                                 - 
 -       #inliers #(correspondences found) (time needed to compute the visual words, in seconds) (time needed for linear  - 
 -       search, in seconds) (time needed for RANSAC, in seconds) (total time needed, in seconds)                                                                                                                                            - 
________________________________________________________________________________

Process finished with exit code 255`

**Comment by tsattler** [comment]
This is the standard output you get if you call the program with no or an insufficient number of parameters. Please see the readme file for details on how to run the executables.

**Comment by alexs7** [comment]
@xiaoxiaobx If it helps there is also a runnable docker example here in this repo: https://github.com/pangfumin/ACG-localizer

**Comment by xiaoxiaobx** [comment]
Hi,@tsattler
How to get dataset ?

**Comment by tsattler** [comment]
@xiaoxiaobx You can find most datasets that are typically used on the internet (on project pages for the corresponding papers, via links in the papers, or on the websites of the authors). If I remember correctly, the website of my CVPR 2017 tutorial provided links to some datasets, but I don't have the link to that page at the moment (you can find it on the CVPR 2017 website).
