### ISSUE TITLE
how to get the cluster file when running compute_desc_assignments

### ISSUE THREAD

**Issue by tiger20** [alexs7/ACG_Localizer#2]
One of the inputs of the executable compute_desc_assignments is a text file containing sift descriptors.How can I get such a file? Can you offer a link to download it?
![image](https://user-images.githubusercontent.com/12908391/75431454-d65b8300-5987-11ea-95a5-116ad5719036.png)

**Comment by alexs7** [comment]
I am sorry you will have to contact the author for this as I haven't run the code yet.

**Comment by hm510** [comment]
> One of the inputs of the executable compute_desc_assignments is a text file containing sift descriptors.How can I get such a file? Can you offer a link to download it?
> ![image](https://user-images.githubusercontent.com/12908391/75431454-d65b8300-5987-11ea-95a5-116ad5719036.png)

have you fixed that problem?

**Comment by vcrg** [comment]
@hm510 no yet. Are you having the same issue ? Did you try the docker version ?

**Comment by alexs7** [comment]
@hm510 No not yet. Are you having the same issue ? Did you try the docker version ?
