### ISSUE TITLE
make error

### ISSUE THREAD

**Issue by fred-och-karlek** [alexs7/ACG_Localizer#3]
Hi,

I got some errors when making the files. As shown in the following picture, this is what I got first,

![Screenshot from 2020-03-26 00-28-01](https://user-images.githubusercontent.com/43069216/77595277-0b141900-6ef9-11ea-83e1-eeac0691ac18.png)

According to this link, https://github.com/openalpr/openalpr/issues/528, I solved the very first error but got some other errors as you can see below.

![Screenshot from 2020-03-26 00-28-20](https://user-images.githubusercontent.com/43069216/77595285-10716380-6ef9-11ea-88dd-6236a5a5789b.png)

I have no clue yet, could you please help me ?

**Comment by alexs7** [comment]
Hello sorry for the late reply. Which compiler are you using?

**Comment by fred-och-karlek** [comment]
Hi, thanks for your reply!
the compiler is
gcc version 5.5.0 20171010 (Ubuntu 5.5.0-12ubuntu1)

**Comment by alexs7** [comment]
Maybe try gcc 6?

Also there is a runnable docker here: https://github.com/pangfumin/ACG-localizer
